#!/usr/bin/env bash
# Auto-generated by ShAuRyA_Supplymind/features/receipts.py
# Verify: TimesFM-CP WTI deviation from 95% nominal
# Expected: 0.04999999999999993
# Git SHA at issuance: 6729e540069a
set -e
cd "$(dirname "$0")/../.."
python -c "import json; d=json.load(open('v3_arcadia/results/R3_TIMESFM_QUANTILE.json'));print(d['targets']['DCOILWTICO']['timesfm_conf=0.95']['dev_from_nominal'])"
