#!/usr/bin/env bash
# Auto-generated by ShAuRyA_Supplymind/features/receipts.py
# Verify: 2-judge panel Krippendorff ordinal alpha on 26 crisis scenarios
# Expected: 0.7499056959637873
# Git SHA at issuance: 74567ce7e577
set -e
cd "$(dirname "$0")/../.."
python -c "import json; print(json.load(open(r'v3_arcadia/results/R4_DANGEROUS_V2_ABLATION.json'))['agreement_primary_panel']['krippendorff_alpha_ordinal'])"
