#!/usr/bin/env bash
# Auto-generated by ShAuRyA_Supplymind/features/receipts.py
# Verify: BEIR out-of-domain nDCG@10 (Snowflake) on 26 Wiki crisis articles
# Expected: 0.9709860394574094
# Git SHA at issuance: 6729e540069a
set -e
cd "$(dirname "$0")/../.."
python -c "import json; print(json.load(open(r'v3_arcadia/results/R5_BEIR_MANUAL.json'))['our_results']['snowflake-arctic-l']['mean_ndcg@10'])"
