#!/usr/bin/env bash
# Auto-generated by ShAuRyA_Supplymind/features/receipts.py
# Verify: Per-horizon conformal deviation at 95% nominal, WTI ARIMA
# Expected: 0.023809523809523836
# Git SHA at issuance: 74567ce7e577
set -e
cd "$(dirname "$0")/../.."
python -c "import json; d=json.load(open('v3_arcadia/results/R6_AQUA_REGIA_V2.json'));c=d['results']['DCOILWTICO']['arima']['conf=0.95'];print(abs(c['perhorizon_coverage_mean']-c['nominal_coverage']))"
