#!/usr/bin/env bash
# Auto-generated by ShAuRyA_Supplymind/features/receipts.py
# Verify: GNN easy-graph MAE reduction vs MLP baseline (%)
# Expected: 48.0247837147887
# Git SHA at issuance: 02251e94dc01
set -e
cd "$(dirname "$0")/../.."
python -c "import json; print(json.load(open(r'v3_arcadia/results/R6_PROVIDER_V2.json'))['graphs']['easy']['improvement_vs_mlp_pct'])"
