#!/usr/bin/env bash
# Auto-generated by ShAuRyA_Supplymind/features/receipts.py
# Verify: MaskablePPO easy-task reward lift vs plain PPO (+%)
# Expected: 26.768743400211196
# Git SHA at issuance: a0738ad89aa2
set -e
cd "$(dirname "$0")/../.."
python -c "import json; print(json.load(open(r'v3_arcadia/results/R6_GETHSEMANE_MASKING_ABLATION.json'))['action_masking_contribution']['reward_pct_delta'])"
