#!/usr/bin/env bash
# Auto-generated by ShAuRyA_Supplymind/features/receipts.py
# Verify: Best CI95-lower accepted by autoresearch orchestrator (bootstrap 1000)
# Expected: 0.4035
# Git SHA at issuance: 6729e540069a
set -e
cd "$(dirname "$0")/../.."
python -c "import json; d=json.load(open('ShAuRyA_Supplymind/autoresearch/state.json'));print(d['best']['metric']['ci95_lower']) if d.get('best') else print('none')"
