#!/usr/bin/env bash
# Auto-generated by ShAuRyA_Supplymind/features/receipts.py
# Verify: FRED Brent crude spot price as ingested on 2026-04-21 ($/bbl)
# Expected: 123.28
# Git SHA at issuance: a0738ad89aa2
set -e
cd "$(dirname "$0")/../.."
python -c "import sqlite3, json; c=sqlite3.connect('ShAuRyA_Supplymind/realtime/events.db');r=c.execute('SELECT meta_json FROM events WHERE source=? ORDER BY ts_unix DESC LIMIT 1', ('fred_brent',)).fetchone();print(json.loads(r[0])['latest_price']) if r else print('no-data')"
