#!/usr/bin/env bash
# Auto-generated by ShAuRyA_Supplymind/features/receipts.py
# Verify: v4 SPOF articulation-point F1 (mean across 3 graphs)
# Expected: 1.0
# Git SHA at issuance: 6729e540069a
set -e
cd "$(dirname "$0")/../.."
python -c "import json; print(json.load(open(r'ShAuRyA_Supplymind/features/R6_SPOF_V2.json'))['summary']['v2_mean_f1'])"
