#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    TimesFM residual-conformal on WTI at 95%: |coverage - nominal| = 0.050
# Expected: '0.050' (==)
# Hardware at last run: <pending-first-run>
# Runtime:  0.0s
set -euo pipefail
echo "[R3_TimesFM_CP_WTI_dev95] command:"
echo '> python -m v3_arcadia.20_past_self.r3_timesfm_residual_quantile --out /tmp/r3_tfm.json'
python -m v3_arcadia.20_past_self.r3_timesfm_residual_quantile --out /tmp/r3_tfm.json
echo
echo "[R3_TimesFM_CP_WTI_dev95] extraction:"
echo '> python -c "import json; print(round(abs(json.load(open(r\"/tmp/r3_tfm.json\")).get(\"DCOILWTICO\",{}).get(\"conformal_coverage_dev_95\",0)),3))"'
python -c "import json; print(round(abs(json.load(open(r\"/tmp/r3_tfm.json\")).get(\"DCOILWTICO\",{}).get(\"conformal_coverage_dev_95\",0)),3))"
echo
echo "[R3_TimesFM_CP_WTI_dev95] expected: 0.050"
echo "[R3_TimesFM_CP_WTI_dev95] comparator: =="
