#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    2-judge (Qwen-14B + Mistral-Nemo) Krippendorff ordinal alpha on 26 scenarios equals 0.7499 (the raw 3-judge alpha is only 0.210  -  see versions/v3_arcadia/results/R4_DANGEROUS_V2_REPORT.md)
# Expected: '0.7499' (==)
# Hardware at last run: NVIDIA GeForce RTX 4080 Laptop GPU 11GB VRAM
# Runtime:  0.0s
set -euo pipefail
echo "[R4_2JUDGE_Krippendorff_alpha] command:"
echo '> python versions/v3_arcadia/30_dangerous/r4_ablation_and_baseline.py --out /tmp/r4_ab.json'
python versions/v3_arcadia/30_dangerous/r4_ablation_and_baseline.py --out /tmp/r4_ab.json
echo
echo "[R4_2JUDGE_Krippendorff_alpha] extraction:"
echo '> python -c "import json; print(json.load(open(r\"/tmp/r4_ab.json\")).get(\"agreement_primary_panel\",{}).get(\"krippendorff_alpha_ordinal\"))"'
python -c "import json; print(json.load(open(r\"/tmp/r4_ab.json\")).get(\"agreement_primary_panel\",{}).get(\"krippendorff_alpha_ordinal\"))"
echo
echo "[R4_2JUDGE_Krippendorff_alpha] expected: 0.7499"
echo "[R4_2JUDGE_Krippendorff_alpha] comparator: =="
