#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    Cohen weighted kappa Qwen-14B vs Mistral-Nemo equals 0.747
# Expected: '0.747' (==)
# Hardware at last run: <pending-first-run>
# Runtime:  0.0s
set -euo pipefail
echo "[R4_Cohen_kappa_QwenMistral] command:"
echo '> python -m v3_arcadia.30_dangerous.r4_ablation_and_baseline --out /tmp/r4_kappa.json'
python -m v3_arcadia.30_dangerous.r4_ablation_and_baseline --out /tmp/r4_kappa.json
echo
echo "[R4_Cohen_kappa_QwenMistral] extraction:"
echo '> python -c "import json; blob=json.load(open(r\"/tmp/r4_kappa.json\")); print(blob.get(\"pairwise_weighted_kappa\",{}).get(\"qwen_mistral\") or blob.get(\"agreement_primary_panel\",{}).get(\"cohen_kappa_qwen_mistral\"))"'
python -c "import json; blob=json.load(open(r\"/tmp/r4_kappa.json\")); print(blob.get(\"pairwise_weighted_kappa\",{}).get(\"qwen_mistral\") or blob.get(\"agreement_primary_panel\",{}).get(\"cohen_kappa_qwen_mistral\"))"
echo
echo "[R4_Cohen_kappa_QwenMistral] expected: 0.747"
echo "[R4_Cohen_kappa_QwenMistral] comparator: =="
