#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    Snowflake-Arctic-L nDCG@10 on 26 Wikipedia-crisis BEIR subset equals 0.971
# Expected: '0.971' (==)
# Hardware at last run: <pending-first-run>
# Runtime:  0.0s
set -euo pipefail
echo "[R5_BEIR_snowflake_nDCG10] command:"
echo '> python -m v3_arcadia.40_granite.r5_manual_beir --out /tmp/r5_beir.json'
python -m v3_arcadia.40_granite.r5_manual_beir --out /tmp/r5_beir.json
echo
echo "[R5_BEIR_snowflake_nDCG10] extraction:"
echo '> python -c "import json; print(json.load(open(r\"/tmp/r5_beir.json\")).get(\"our_results\",{}).get(\"snowflake-arctic-l\",{}).get(\"mean_ndcg@10\"))"'
python -c "import json; print(json.load(open(r\"/tmp/r5_beir.json\")).get(\"our_results\",{}).get(\"snowflake-arctic-l\",{}).get(\"mean_ndcg@10\"))"
echo
echo "[R5_BEIR_snowflake_nDCG10] expected: 0.971"
echo "[R5_BEIR_snowflake_nDCG10] comparator: =="
