#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    mxbai-embed-large P@1 on 53 precise SupplyMind queries equals 0.9622 (headline value committed in versions/v3_arcadia/results/R5_GRANITE_HARD.json)
# Expected: '0.9622' (==)
# Hardware at last run: NVIDIA GeForce RTX 4080 Laptop GPU 11GB VRAM
# Runtime:  0.0s
set -euo pipefail
echo "[R5_GRANITE_mxbai_P1] command:"
echo '> python versions/v3_arcadia/40_granite/r5_rag_beast.py --pipeline mxbai_bi --out /tmp/r5_granite_p1.json'
python versions/v3_arcadia/40_granite/r5_rag_beast.py --pipeline mxbai_bi --out /tmp/r5_granite_p1.json
echo
echo "[R5_GRANITE_mxbai_P1] extraction:"
echo '> python -c "import json; print(json.load(open(r\"/tmp/r5_granite_p1.json\")).get(\"pipelines\",{}).get(\"P2_mxbai_bi\",{}).get(\"p1\"))"'
python -c "import json; print(json.load(open(r\"/tmp/r5_granite_p1.json\")).get(\"pipelines\",{}).get(\"P2_mxbai_bi\",{}).get(\"p1\"))"
echo
echo "[R5_GRANITE_mxbai_P1] expected: 0.9622"
echo "[R5_GRANITE_mxbai_P1] comparator: =="
