#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    mxbai-embed-large MRR on 53 precise queries equals 0.9780
# Expected: '0.9780' (==)
# Hardware at last run: <pending-first-run>
# Runtime:  0.0s
set -euo pipefail
echo "[R5_GRANITE_mxbai_MRR] command:"
echo '> python -m v3_arcadia.40_granite.r5_rag_beast --pipeline mxbai_bi --out /tmp/r5_granite_mrr.json'
python -m v3_arcadia.40_granite.r5_rag_beast --pipeline mxbai_bi --out /tmp/r5_granite_mrr.json
echo
echo "[R5_GRANITE_mxbai_MRR] extraction:"
echo '> python -c "import json; print(json.load(open(r\"/tmp/r5_granite_mrr.json\")).get(\"pipelines\",{}).get(\"P2_mxbai_bi\",{}).get(\"mrr\"))"'
python -c "import json; print(json.load(open(r\"/tmp/r5_granite_mrr.json\")).get(\"pipelines\",{}).get(\"P2_mxbai_bi\",{}).get(\"mrr\"))"
echo
echo "[R5_GRANITE_mxbai_MRR] expected: 0.9780"
echo "[R5_GRANITE_mxbai_MRR] comparator: =="
