#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    Per-horizon split-conformal on DCOILWTICO at 95% nominal: |coverage - nominal| = 0.0238
# Expected: '0.0238' (==)
# Hardware at last run: <pending-first-run>
# Runtime:  0.0s
set -euo pipefail
echo "[R6_AquaRegia_WTI_dev95] command:"
echo '> python -m v3_arcadia.80_aqua_regia.r6_per_horizon_conformal --out /tmp/r6_aqua.json'
python -m v3_arcadia.80_aqua_regia.r6_per_horizon_conformal --out /tmp/r6_aqua.json
echo
echo "[R6_AquaRegia_WTI_dev95] extraction:"
echo '> python -c "import json; print(round(abs(json.load(open(r\"/tmp/r6_aqua.json\")).get(\"DCOILWTICO\",{}).get(\"conformal_coverage_dev_95\",0)),4))"'
python -c "import json; print(round(abs(json.load(open(r\"/tmp/r6_aqua.json\")).get(\"DCOILWTICO\",{}).get(\"conformal_coverage_dev_95\",0)),4))"
echo
echo "[R6_AquaRegia_WTI_dev95] expected: 0.0238"
echo "[R6_AquaRegia_WTI_dev95] comparator: =="
