#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    GCN beats MLP on easy graph by 48.02 percent MAE reduction
# Expected: '48.0247' (==)
# Hardware at last run: <pending-first-run>
# Runtime:  0.0s
set -euo pipefail
echo "[R6_GCN_easy_MAE_vs_MLP] command:"
echo '> python -m v3_arcadia.70_provider.r6_gnn_arrival_time --out /tmp/r6_gnn.json'
python -m v3_arcadia.70_provider.r6_gnn_arrival_time --out /tmp/r6_gnn.json
echo
echo "[R6_GCN_easy_MAE_vs_MLP] extraction:"
echo '> python -c "import json; print(round(100*json.load(open(r\"/tmp/r6_gnn.json\")).get(\"easy\",{}).get(\"mae_reduction_pct\",0),4))"'
python -c "import json; print(round(100*json.load(open(r\"/tmp/r6_gnn.json\")).get(\"easy\",{}).get(\"mae_reduction_pct\",0),4))"
echo
echo "[R6_GCN_easy_MAE_vs_MLP] expected: 48.0247"
echo "[R6_GCN_easy_MAE_vs_MLP] comparator: =="
