#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    MaskablePPO over PPO lift on easy_typhoon_response equals 26.77%
# Expected: '26.77' (==)
# Hardware at last run: <pending-first-run>
# Runtime:  0.0s
set -euo pipefail
echo "[R6_MaskingAblation_easy_lift] command:"
echo '> python -m v3_arcadia.50_gethsemane.r6_unmasked_ablation --out /tmp/r6_mask.json'
python -m v3_arcadia.50_gethsemane.r6_unmasked_ablation --out /tmp/r6_mask.json
echo
echo "[R6_MaskingAblation_easy_lift] extraction:"
echo '> python -c "import json; print(round(100*(json.load(open(r\"/tmp/r6_mask.json\")).get(\"easy_typhoon_response\",{}).get(\"masking_lift_pct\",0)),2))"'
python -c "import json; print(round(100*(json.load(open(r\"/tmp/r6_mask.json\")).get(\"easy_typhoon_response\",{}).get(\"masking_lift_pct\",0)),2))"
echo
echo "[R6_MaskingAblation_easy_lift] expected: 26.77"
echo "[R6_MaskingAblation_easy_lift] comparator: =="
