#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    FRED Brent polling returns a live April-2026 value parseable as USD/bbl
# Expected: '60' (in_range)
# Hardware at last run: <pending-first-run>
# Runtime:  0.0s
set -euo pipefail
echo "[V4_Live_Brent_202604] command:"
echo '> python -m versions.v4_arcadia_live.realtime.sources.fred_brent --latest-only'
python -m versions.v4_arcadia_live.realtime.sources.fred_brent --latest-only
echo
echo "[V4_Live_Brent_202604] extraction:"
echo '> python -c "import sys; out=sys.stdin.read(); import re; m=re.search(r\"(\\d+\\.\\d+)\", out); print(m.group(1) if m else \"\")"'
python -c "import sys; out=sys.stdin.read(); import re; m=re.search(r\"(\\d+\\.\\d+)\", out); print(m.group(1) if m else \"\")"
echo
echo "[V4_Live_Brent_202604] expected: 60"
echo "[V4_Live_Brent_202604] comparator: in_range"
