#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    FRED Brent polling returns a live value parseable as USD/bbl in the plausible $60-$250 band
# Expected: '60' (in_range)
# Hardware at last run: NVIDIA GeForce RTX 4080 Laptop GPU 11GB VRAM
# Runtime:  0.0s
set -euo pipefail
echo "[V4_Live_Brent_202604] command:"
echo '> python -m versions.v4_arcadia_live.realtime.sources.fred_brent'
python -m versions.v4_arcadia_live.realtime.sources.fred_brent
echo
echo "[V4_Live_Brent_202604] extraction:"
echo '> python -c "import sys,re; out=sys.stdin.read(); m=re.search(r\"(\\d+\\.\\d+)\", out); print(m.group(1) if m else \"\")"'
python -c "import sys,re; out=sys.stdin.read(); m=re.search(r\"(\\d+\\.\\d+)\", out); print(m.group(1) if m else \"\")"
echo
echo "[V4_Live_Brent_202604] expected: 60"
echo "[V4_Live_Brent_202604] comparator: in_range"
