#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    SPOF detector v2 F1 on 3 real supply-chain graphs equals 1.000
# Expected: '1.0' (==)
# Hardware at last run: <pending-first-run>
# Runtime:  0.0s
set -euo pipefail
echo "[V4_SPOF_V2_F1] command:"
echo '> python -m versions.v4_arcadia_live.features.spof_v2 --eval-all --out /tmp/spof.json'
python -m versions.v4_arcadia_live.features.spof_v2 --eval-all --out /tmp/spof.json
echo
echo "[V4_SPOF_V2_F1] extraction:"
echo '> python -c "import json; print(json.load(open(r\"/tmp/spof.json\")).get(\"overall_f1\"))"'
python -c "import json; print(json.load(open(r\"/tmp/spof.json\")).get(\"overall_f1\"))"
echo
echo "[V4_SPOF_V2_F1] expected: 1.0"
echo "[V4_SPOF_V2_F1] comparator: =="
