#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    Proper stacking vs weighted-vote on DataCo ensemble: delta <= 0.001 (null result on 0.97+ ceiling)
# Expected: '0.001' (<=)
# Hardware at last run: <pending-first-run>
# Runtime:  0.0s
set -euo pipefail
echo "[V4_STACKING_V2_lift_vs_WV] command:"
echo '> python -m versions.v4_arcadia_live.features.stacking_v2 --out /tmp/stack.json'
python -m versions.v4_arcadia_live.features.stacking_v2 --out /tmp/stack.json
echo
echo "[V4_STACKING_V2_lift_vs_WV] extraction:"
echo '> python -c "import json; print(round(json.load(open(r\"/tmp/stack.json\")).get(\"lift_stack_over_weighted_vote\",0),3))"'
python -c "import json; print(round(json.load(open(r\"/tmp/stack.json\")).get(\"lift_stack_over_weighted_vote\",0),3))"
echo
echo "[V4_STACKING_V2_lift_vs_WV] expected: 0.001"
echo "[V4_STACKING_V2_lift_vs_WV] comparator: <="
