#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    Proper stacking beats weighted-vote on the DataCo ensemble by only a negligible AUC margin (measured +0.0027 on a 0.98+ ceiling; asserts lift <= 0.01 = near-null)
# Expected: '0.01' (<=)
# Hardware at last run: NVIDIA GeForce RTX 4080 Laptop GPU 11GB VRAM
# Runtime:  78.52s
set -euo pipefail
echo "[V4_STACKING_V2_lift_vs_WV] command:"
echo '> python -m versions.v4_arcadia_live.features.stacking_v2 --save'
python -m versions.v4_arcadia_live.features.stacking_v2 --save
echo
echo "[V4_STACKING_V2_lift_vs_WV] extraction:"
echo '> python -c "import json; print(round(json.load(open(r\"versions/v4_arcadia_live/features/R15_STACKING_V2.json\")).get(\"lift_stacking_vs_wv_auc\",0),4))"'
python -c "import json; print(round(json.load(open(r\"versions/v4_arcadia_live/features/R15_STACKING_V2.json\")).get(\"lift_stacking_vs_wv_auc\",0),4))"
echo
echo "[V4_STACKING_V2_lift_vs_WV] expected: 0.01"
echo "[V4_STACKING_V2_lift_vs_WV] comparator: <="
