#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    SPOF detector v2 (articulation-point) mean F1 over easy/medium/hard graphs equals 1.000
# Expected: '1.0' (==)
# Hardware at last run: NVIDIA GeForce RTX 4080 Laptop GPU 11GB VRAM
# Runtime:  0.54s
set -euo pipefail
echo "[V4_SPOF_V2_F1] command:"
echo '> python -m versions.v4_arcadia_live.features.spof_v2 --graph all --save'
python -m versions.v4_arcadia_live.features.spof_v2 --graph all --save
echo
echo "[V4_SPOF_V2_F1] extraction:"
echo '> python -c "import json; print(json.load(open(r\"versions/v4_arcadia_live/features/R6_SPOF_V2.json\")).get(\"summary\",{}).get(\"v2_mean_f1\"))"'
python -c "import json; print(json.load(open(r\"versions/v4_arcadia_live/features/R6_SPOF_V2.json\")).get(\"summary\",{}).get(\"v2_mean_f1\"))"
echo
echo "[V4_SPOF_V2_F1] expected: 1.0"
echo "[V4_SPOF_V2_F1] comparator: =="
