#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    v3 core (173) + v4 new (76) = 249 total tests pass
# Expected: '249' (regex)
# Hardware at last run: <pending-first-run>
# Runtime:  0.0s
set -euo pipefail
echo "[V4_Tests_Total] command:"
echo '> pytest tests/ versions/v4_arcadia_live/tests/ -q --tb=no'
pytest tests/ versions/v4_arcadia_live/tests/ -q --tb=no
echo
echo "[V4_Tests_Total] extraction:"
echo '> grep -oE "[0-9]+ passed" || true'
grep -oE "[0-9]+ passed" || true
echo
echo "[V4_Tests_Total] expected: 249"
echo "[V4_Tests_Total] comparator: regex"
