#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    v3 core (184) + v4 new (77) = 261 total tests pass (measured 2026-07-02)
# Expected: '261' (regex)
# Hardware at last run: NVIDIA GeForce RTX 4080 Laptop GPU 11GB VRAM
# Runtime:  248.64s
set -euo pipefail
echo "[V4_Tests_Total] command:"
echo '> pytest tests/ versions/v4_arcadia_live/tests/ -q --tb=no | grep -oE "[0-9]+ passed"'
pytest tests/ versions/v4_arcadia_live/tests/ -q --tb=no | grep -oE "[0-9]+ passed"
echo
echo "[V4_Tests_Total] extraction:"
echo '> echo "(no extraction stage)"'
echo "(no extraction stage)"
echo
echo "[V4_Tests_Total] expected: 261"
echo "[V4_Tests_Total] comparator: regex"
