#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    DPO preference-pair builder produces >= 20 pairs from 26 scenarios (the DPO fine-tune itself never completed  -  this receipt covers only the pair builder)
# Expected: '20' (>=)
# Hardware at last run: NVIDIA GeForce RTX 4080 Laptop GPU 11GB VRAM
# Runtime:  0.15s
set -euo pipefail
echo "[V5_DPO_JUDGE_preference_pairs_built] command:"
echo '> python -m versions.v5_phoenix.roll_integration.dpo_judge.prepare_preference_data'
python -m versions.v5_phoenix.roll_integration.dpo_judge.prepare_preference_data
echo
echo "[V5_DPO_JUDGE_preference_pairs_built] extraction:"
echo '> python -c "print(sum(1 for _ in open(r\"versions/v5_phoenix/roll_integration/dpo_judge/data/preference_pairs.jsonl\", encoding=\"utf-8\")))"'
python -c "print(sum(1 for _ in open(r\"versions/v5_phoenix/roll_integration/dpo_judge/data/preference_pairs.jsonl\", encoding=\"utf-8\")))"
echo
echo "[V5_DPO_JUDGE_preference_pairs_built] expected: 20"
echo "[V5_DPO_JUDGE_preference_pairs_built] comparator: >="
