#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    Phoenix v5 test suite passes without affecting v4 tests (measured 16 passed)
# Expected: 'passed' (regex)
# Hardware at last run: NVIDIA GeForce RTX 4080 Laptop GPU 11GB VRAM
# Runtime:  3.72s
set -euo pipefail
echo "[V5_Phoenix_tests_green] command:"
echo '> pytest versions/v5_phoenix/tests/ -q --tb=no | grep -oE "[0-9]+ passed"'
pytest versions/v5_phoenix/tests/ -q --tb=no | grep -oE "[0-9]+ passed"
echo
echo "[V5_Phoenix_tests_green] extraction:"
echo '> echo "(no extraction stage)"'
echo "(no extraction stage)"
echo
echo "[V5_Phoenix_tests_green] expected: passed"
echo "[V5_Phoenix_tests_green] comparator: regex"
