#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    Phoenix v5 test suite passes without affecting v4 tests
# Expected: 'passed' (regex)
# Hardware at last run: NVIDIA GeForce RTX 4080 Laptop GPU 11GB VRAM
# Runtime:  3.59s
set -euo pipefail
echo "[V5_Phoenix_tests_green] command:"
echo '> pytest versions/v5_phoenix/tests/ -q --tb=no'
pytest versions/v5_phoenix/tests/ -q --tb=no
echo
echo "[V5_Phoenix_tests_green] extraction:"
echo '> grep -oE "[0-9]+ passed" || true'
grep -oE "[0-9]+ passed" || true
echo
echo "[V5_Phoenix_tests_green] expected: passed"
echo "[V5_Phoenix_tests_green] comparator: regex"
