#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    supplymind-skills pack contains 3 SKILL.md files + plugin.json
# Expected: '4' (>=)
# Hardware at last run: NVIDIA GeForce RTX 4080 Laptop GPU 11GB VRAM
# Runtime:  0.12s
set -euo pipefail
echo "[V5_Skill_pack_shipped] command:"
echo '> python -c "import glob; [print(p) for p in glob.glob('versions/v5_phoenix/supplymind_skills/*/SKILL.md') + glob.glob('versions/v5_phoenix/supplymind_skills/plugin.json')]"'
python -c "import glob; [print(p) for p in glob.glob('versions/v5_phoenix/supplymind_skills/*/SKILL.md') + glob.glob('versions/v5_phoenix/supplymind_skills/plugin.json')]"
echo
echo "[V5_Skill_pack_shipped] extraction:"
echo '> python -c "import glob; print(len(glob.glob('versions/v5_phoenix/supplymind_skills/*/SKILL.md') + glob.glob('versions/v5_phoenix/supplymind_skills/plugin.json')))"'
python -c "import glob; print(len(glob.glob('versions/v5_phoenix/supplymind_skills/*/SKILL.md') + glob.glob('versions/v5_phoenix/supplymind_skills/plugin.json')))"
echo
echo "[V5_Skill_pack_shipped] expected: 4"
echo "[V5_Skill_pack_shipped] comparator: >="
