#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    supplymind-skills pack contains 3 SKILL.md files + plugin.json
# Expected: '4' (>=)
# Hardware at last run: NVIDIA GeForce RTX 4080 Laptop GPU 11GB VRAM
# Runtime:  0.04s
set -euo pipefail
echo "[V5_Skill_pack_shipped] command:"
echo '> ls versions/v5_phoenix/supplymind_skills/*/SKILL.md versions/v5_phoenix/supplymind_skills/plugin.json'
ls versions/v5_phoenix/supplymind_skills/*/SKILL.md versions/v5_phoenix/supplymind_skills/plugin.json
echo
echo "[V5_Skill_pack_shipped] extraction:"
echo '> ls versions/v5_phoenix/supplymind_skills/*/SKILL.md versions/v5_phoenix/supplymind_skills/plugin.json | wc -l'
ls versions/v5_phoenix/supplymind_skills/*/SKILL.md versions/v5_phoenix/supplymind_skills/plugin.json | wc -l
echo
echo "[V5_Skill_pack_shipped] expected: 4"
echo "[V5_Skill_pack_shipped] comparator: >="
