#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    Counterfactual Twin on severity=0.85 yields positive median $ saved vs no-action
# Expected: '0' (>=)
# Hardware at last run: NVIDIA GeForce RTX 4080 Laptop GPU 11GB VRAM
# Runtime:  48761.59s
set -euo pipefail
echo "[V5_Twin_savings_gt_zero] command:"
echo '> python -m versions.v5_phoenix.counterfactual_twin.twin --severity 0.85 --brent 123 --rollouts 30 --out /tmp/twin.json'
python -m versions.v5_phoenix.counterfactual_twin.twin --severity 0.85 --brent 123 --rollouts 30 --out /tmp/twin.json
echo
echo "[V5_Twin_savings_gt_zero] extraction:"
echo '> python -c "import json; print(json.load(open(r\"/tmp/twin.json\")).get(\"savings_vs_no_action_usd\"))"'
python -c "import json; print(json.load(open(r\"/tmp/twin.json\")).get(\"savings_vs_no_action_usd\"))"
echo
echo "[V5_Twin_savings_gt_zero] expected: 0"
echo "[V5_Twin_savings_gt_zero] comparator: >="
