#!/usr/bin/env bash
# Auto-generated by Phoenix v5 receipts framework.
# Claim:    Counterfactual Twin on severity=0.85 yields positive median $ saved vs no-action (measured +$135.5M savings on 20 rollouts, 2026-07-02)
# Expected: '0' (>=)
# Hardware at last run: NVIDIA GeForce RTX 4080 Laptop GPU 11GB VRAM
# Runtime:  21.73s
set -euo pipefail
echo "[V5_Twin_savings_gt_zero] command:"
echo '> python -m versions.v5_phoenix.counterfactual_twin.twin --severity 0.85 --brent 123 --rollouts 20 --task easy_typhoon_response --out versions/v5_phoenix/experiments/twin/V5_receipt_run.json'
python -m versions.v5_phoenix.counterfactual_twin.twin --severity 0.85 --brent 123 --rollouts 20 --task easy_typhoon_response --out versions/v5_phoenix/experiments/twin/V5_receipt_run.json
echo
echo "[V5_Twin_savings_gt_zero] extraction:"
echo '> python -c "import json; print(json.load(open(r\"versions/v5_phoenix/experiments/twin/V5_receipt_run.json\", encoding=\"utf-8\")).get(\"savings_vs_no_action_usd\"))"'
python -c "import json; print(json.load(open(r\"versions/v5_phoenix/experiments/twin/V5_receipt_run.json\", encoding=\"utf-8\")).get(\"savings_vs_no_action_usd\"))"
echo
echo "[V5_Twin_savings_gt_zero] expected: 0"
echo "[V5_Twin_savings_gt_zero] comparator: >="
