"""
lab_notebook.py — Auto-generate human-readable lab notebook entries.

Accepted experiments append to AUTORESEARCH_LAB_NOTEBOOK.md (sorted by delta).
Rejected experiments append to AUTORESEARCH_REJECTED.md (chronological).

Every entry includes:
    - timestamp
    - experiment name + hypothesis
    - metric table (before/after with CI95)
    - diff summary
    - plot links (if present)
    - surprise flag (|actual - expected| > 0.03)
"""
from __future__ import annotations

import json
import logging
import re
import time
from datetime import datetime
from difflib import unified_diff
from pathlib import Path
from typing import Optional

import numpy as np

logger = logging.getLogger(__name__)

AUTORESEARCH_DIR = Path(__file__).resolve().parent
ACCEPTED_MD = AUTORESEARCH_DIR / "AUTORESEARCH_LAB_NOTEBOOK.md"
REJECTED_MD = AUTORESEARCH_DIR / "AUTORESEARCH_REJECTED.md"


def _init_notebook(path: Path, title: str) -> None:
    if path.exists():
        return
    path.write_text(
        f"# {title}\n\n"
        f"*Auto-generated by `lab_notebook.py`. Do not hand-edit; append via `log_entry()`.*\n\n"
        "---\n\n",
        encoding="utf-8",
    )


def _parse_expected_delta(s: str) -> Optional[float]:
    """Extract a midpoint float from a string like '+0.02 to +0.06'."""
    m = re.findall(r"[+-]?\d*\.?\d+", s or "")
    if not m:
        return None
    vals = [float(x) for x in m]
    return sum(vals) / len(vals)


def _format_metric_table(before: dict, after: dict, delta: float) -> str:
    def fmt(m: dict, key: str) -> str:
        if m is None:
            return "—"
        v = m.get(key, 0.0)
        return f"{v:.4f}" if isinstance(v, (int, float)) else str(v)

    lines = [
        "| metric        | before (best) | after (this) | delta |",
        "|---------------|---------------|--------------|-------|",
        f"| mean          | {fmt(before,'mean')} | {fmt(after,'mean')} |       |",
        f"| std           | {fmt(before,'std')} | {fmt(after,'std')} |       |",
        f"| **ci95_lower**| **{fmt(before,'ci95_lower')}** | **{fmt(after,'ci95_lower')}** | **{delta:+.4f}** |",
        f"| ci95_upper    | {fmt(before,'ci95_upper')} | {fmt(after,'ci95_upper')} |       |",
        f"| n             | {fmt(before,'n')} | {fmt(after,'n')} |       |",
    ]
    return "\n".join(lines)


def _surprise_flag(expected: Optional[float], actual: float, threshold: float = 0.03) -> str:
    if expected is None:
        return ""
    diff = abs(actual - expected)
    if diff > threshold:
        direction = "better" if actual > expected else "worse"
        return f"\n**SURPRISE ({direction} than expected by {diff:.3f})**: actual={actual:+.3f} vs expected={expected:+.3f}\n"
    return ""


def _diff_summary(old_code: str, new_code: str) -> str:
    lines = list(
        unified_diff(
            old_code.splitlines(),
            new_code.splitlines(),
            n=1,
            lineterm="",
        )
    )
    added = sum(1 for ln in lines if ln.startswith("+") and not ln.startswith("+++"))
    removed = sum(1 for ln in lines if ln.startswith("-") and not ln.startswith("---"))
    return f"diff: +{added} / -{removed} LOC"


def log_accepted(
    experiment_name: str,
    hypothesis: dict,
    metric_before: Optional[dict],
    metric_after: dict,
    delta: float,
    wall_clock_s: float,
    architecture: str,
    old_code: str,
    new_code: str,
    plot_links: Optional[list[str]] = None,
) -> None:
    """Append an accepted experiment entry."""
    _init_notebook(ACCEPTED_MD, "SupplyMind AutoResearch — Lab Notebook (Accepted)")

    ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    expected = _parse_expected_delta(hypothesis.get("expected_metric_delta", ""))
    surprise = _surprise_flag(expected, delta)

    plot_block = ""
    if plot_links:
        plot_block = "\n**Plots**:\n" + "\n".join(f"- [{p}]({p})" for p in plot_links) + "\n"

    entry = f"""## {ts} — `{experiment_name}` ✅ ACCEPTED

**Hypothesis**: {hypothesis.get('hypothesis', '(none)')}

**Expected delta**: {hypothesis.get('expected_metric_delta', '—')}

**Justification**: {hypothesis.get('justification', '—')}

{_format_metric_table(metric_before, metric_after, delta)}

**Architecture**: `{architecture}`

**Wall clock**: {wall_clock_s:.1f} s

**Diff**: {_diff_summary(old_code, new_code)}

**References**: {', '.join(hypothesis.get('references', [])) or '—'}
{surprise}{plot_block}
---

"""
    with ACCEPTED_MD.open("a", encoding="utf-8") as f:
        f.write(entry)


def log_rejected(
    experiment_name: str,
    hypothesis: dict,
    status: str,
    reason: str,
    metric_before: Optional[dict],
    metric_after: Optional[dict],
    delta: float,
    wall_clock_s: float,
    architecture: str,
) -> None:
    """Append a rejected experiment entry."""
    _init_notebook(REJECTED_MD, "SupplyMind AutoResearch — Rejected Experiments")

    ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    metric_table = ""
    if metric_after is not None:
        metric_table = "\n" + _format_metric_table(metric_before, metric_after, delta) + "\n"

    entry = f"""## {ts} — `{experiment_name}` ❌ REJECTED

**Status**: {status}
**Reason**: {reason}

**Hypothesis**: {hypothesis.get('hypothesis', '(none)')}

**Expected delta**: {hypothesis.get('expected_metric_delta', '—')}
{metric_table}
**Architecture attempted**: `{architecture}`

**Wall clock**: {wall_clock_s:.1f} s

---

"""
    with REJECTED_MD.open("a", encoding="utf-8") as f:
        f.write(entry)


def render_leaderboard(state_path: Path) -> str:
    """Generate a leaderboard markdown from state.json history."""
    if not state_path.exists():
        return "(no state yet)"
    state = json.loads(state_path.read_text())
    history = [h for h in state.get("history", []) if h.get("accepted")]
    if not history:
        return "(no accepted experiments yet)"

    history.sort(key=lambda h: h.get("metric_ci95_lower", 0), reverse=True)

    lines = [
        "| # | experiment | arch | ci95_lower | mean | wall_s |",
        "|---|------------|------|------------|------|--------|",
    ]
    for i, h in enumerate(history[:20], 1):
        lines.append(
            f"| {i} | `{h['experiment_name']}` | {h.get('architecture_summary','?')[:40]} | "
            f"{h.get('metric_ci95_lower',0):.4f} | {h.get('metric_mean',0):.3f} | "
            f"{h.get('wall_clock_s',0):.0f} |"
        )
    return "\n".join(lines)


if __name__ == "__main__":
    import argparse

    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
    parser = argparse.ArgumentParser()
    parser.add_argument("--leaderboard", action="store_true")
    args = parser.parse_args()

    if args.leaderboard:
        print(render_leaderboard(AUTORESEARCH_DIR / "state.json"))
