#!/usr/bin/env bash
# Auto-generated by versions/v4_arcadia_live/features/receipts.py
# Verify: Cohen weighted kappa Qwen-14B x Mistral-Nemo
# Expected: 0.7473841554559043
# Git SHA at issuance: a0738ad89aa2
set -e
cd "$(dirname "$0")/../.."
python -c "import json; print(json.load(open(r'versions/v3_arcadia/results/R4_DANGEROUS_V2_ABLATION.json'))['agreement_primary_panel']['cohen_weighted_kappa_qwen_vs_mistral'])"
