#!/usr/bin/env bash
# Auto-generated by versions/v4_arcadia_live/features/receipts.py
# Verify: RAG MRR on precise queries
# Expected: 0.9779874213836477
# Git SHA at issuance: a0738ad89aa2
set -e
cd "$(dirname "$0")/../.."
python -c "import json; print(json.load(open(r'versions/v3_arcadia/results/R5_GRANITE.json'))['pipelines']['P2_mxbai_bi']['mrr'])"
