#!/usr/bin/env bash
# Auto-generated by versions/v4_arcadia_live/features/receipts.py
# Verify: RAG P@1 on 6,483-chunk real corpus, mxbai bi-encoder
# Expected: 0.9622641509433962
# Git SHA at issuance: a0738ad89aa2
set -e
cd "$(dirname "$0")/../.."
python -c "import json; print(json.load(open(r'versions/v3_arcadia/results/R5_GRANITE.json'))['pipelines']['P2_mxbai_bi']['p1'])"
