#!/usr/bin/env bash
# Auto-generated by versions/v4_arcadia_live/features/receipts.py
# Verify: supplymind-analyst:v5 vs base Qwen on 10 rubric-labeled scenarios
# Expected: 0.8
# Git SHA at issuance: a0738ad89aa2
set -e
cd "$(dirname "$0")/../.."
python -c "import json; print(json.load(open(r'versions/v4_arcadia_live/features/R9_ANALYST_AB_V5.json'))['summary']['exact_acc_lift'])"
