#!/usr/bin/env bash
# Auto-generated by versions/v4_arcadia_live/features/receipts.py
# Verify: Best CI95-lower accepted by autoresearch orchestrator (bootstrap 1000)
# Expected: 0.5514
# Git SHA at issuance: a0738ad89aa2
set -e
cd "$(dirname "$0")/../.."
python -c "import json; d=json.load(open('versions/v4_arcadia_live/autoresearch/state.json'));print(d['best']['metric']['ci95_lower']) if d.get('best') else print('none')"
