#!/usr/bin/env bash
# Auto-generated by versions/v4_arcadia_live/features/receipts.py
# Verify: v4 Stacking v2 AUC lift vs ensemble weighted voting
# Expected: 0.0045
# Git SHA at issuance: a0738ad89aa2
set -e
cd "$(dirname "$0")/../.."
python -c "import json; print(json.load(open(r'versions/v4_arcadia_live/features/R15_STACKING_V2.json'))['lift_stacking_vs_wv_auc'])"
