#!/usr/bin/env bash
# Auto-generated by versions/v4_arcadia_live/features/receipts.py
# Verify: Total test count across v3 + v4
# Expected: tests/test_engine.py::TestSupplyChainGraph::test_load_easy_graph_node_count
tests/test_engine.py::T
# Git SHA at issuance: a0738ad89aa2
set -e
cd "$(dirname "$0")/../.."
python -m pytest tests/ versions/v4_arcadia_live/tests/ --collect-only -q
